### ISSUE TITLE
docker....compose

### ISSUE THREAD

**Issue by Danack** [ssddanbrown/PHP-Docs-Build-Container#1]
> If you're considering a PR to add a new feature or change please open an issue first for discussion to see if it's something that would be accepted.

I (and I think a lot of other people) find docker-compose easier to use than individual docker commands. Would it be okay to add that, and a `runDocs.sh` file to run the tool, rather than having to remember a long command?

**Comment by ssddanbrown** [comment]
> Would it be okay to add that, and a runDocs.sh file to run the tool, rather than having to remember a long command?

Sure! Sounds good. I'd say it'd probably be more versatile to keep using plain docker in that script rather than docker-compose. Happy to still have a separate docker-compose though. Wouldn't want to provide too many options in this script, so maybe it'd use the current working directory as the path to mount for simplicity?

**Comment by ssddanbrown** [comment]
Will therefore close this off, but feel free to PR if still desired!
